# Generated by Django 4.2.3 on 2023-07-18 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=250)),
                ("country", models.CharField(max_length=250)),
                ("state", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=500)),
                ("users", models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bl_number", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[("Enquiry", "Enquiry"), ("Job", "Job")], max_length=255, verbose_name="Job Type"
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("Cargo Collected", "Cargo Collected"),
                            ("Under Export Clearance", "Under Export Clearance"),
                            ("Departed", "Departed"),
                            ("In Transit", "In Transit"),
                            ("Arrived", "Arrived"),
                            ("Under Import Clearance", "Under Import Clearance"),
                            ("Do Collected", "Do Collected"),
                            ("Gate Pass Issued", "Gate Pass Issued"),
                            ("Under Delivery", "Under Delivery"),
                            ("In Warehouse Storage", "In Warehouse Storage"),
                            ("Delivered", "Delivered"),
                            ("Invoiced", "Invoiced"),
                            ("Finished", "Finished"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=255,
                        verbose_name="Job Status",
                    ),
                ),
                ("bayan_number", models.CharField(blank=True, max_length=255, null=True)),
                ("pod", models.CharField(blank=True, max_length=255, null=True)),
                ("poa", models.CharField(blank=True, max_length=255, null=True)),
                ("consignee_name", models.CharField(blank=True, max_length=255, null=True)),
                ("shipper_name", models.CharField(blank=True, max_length=255, null=True)),
                ("client_name", models.CharField(blank=True, max_length=255, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organization.company")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deleted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vouchers",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[("Journal", "Journal"), ("Payment", "Payment"), ("Receipt", "Receipt")],
                        max_length=255,
                        verbose_name="Voucher Type",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("branch", models.CharField(blank=True, max_length=255, null=True)),
                ("gl_date", models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ("start_date", models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ("end_date", models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ("fc_amount", models.CharField(blank=True, max_length=255, null=True)),
                ("amount_sar", models.CharField(blank=True, max_length=255, null=True)),
                ("party_account", models.CharField(blank=True, max_length=255, null=True)),
                ("division", models.CharField(blank=True, max_length=255, null=True)),
                ("naration", models.CharField(blank=True, max_length=255, null=True)),
                ("outstanding_amount", models.CharField(blank=True, max_length=255, null=True)),
                ("dr_account", models.CharField(blank=True, max_length=255, null=True)),
                ("cr_account", models.CharField(blank=True, max_length=255, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organization.job")),
            ],
        ),
        migrations.CreateModel(
            name="Invoices",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bl_number", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("Sales", "Sales"), ("Purchase", "Purchase")],
                        max_length=255,
                        verbose_name="Invoice Type",
                    ),
                ),
                ("consignee_name", models.CharField(blank=True, max_length=255, null=True)),
                ("currency_sar", models.CharField(blank=True, max_length=255, null=True)),
                ("bayan_number", models.CharField(blank=True, max_length=255, null=True)),
                ("shipper_name", models.CharField(blank=True, max_length=255, null=True)),
                ("ex_rate", models.CharField(blank=True, max_length=255, null=True)),
                ("pod", models.CharField(blank=True, max_length=255, null=True)),
                ("poa", models.CharField(blank=True, max_length=255, null=True)),
                ("fc_amount", models.CharField(blank=True, max_length=255, null=True)),
                ("amount_sar", models.CharField(blank=True, max_length=255, null=True)),
                ("ref_data", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("bill_amount", models.CharField(blank=True, max_length=255, null=True)),
                ("narration", models.CharField(blank=True, max_length=255, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organization.company")),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organization.job")),
            ],
        ),
    ]
