# Generated by Django 4.2.3 on 2023-07-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vouchers",
            name="voucher_type",
            field=models.CharField(
                choices=[
                    ("Journal", "Journal"),
                    ("Payment", "Payment"),
                    ("Receipt", "Receipt"),
                    ("Credit", "Credit"),
                    ("Debit", "Debit"),
                ],
                max_length=255,
                verbose_name="Voucher Type",
            ),
        ),
    ]
