# Generated by Django 4.2.3 on 2023-07-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_alter_job_created_by_alter_job_deleted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="enquiry_number",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
