# Generated by Django 4.2.3 on 2023-07-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_job_enquiry_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="branch",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="job_number",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_status",
            field=models.CharField(
                choices=[
                    ("Cargo Collected", "Cargo Collected"),
                    ("Under Export Clearance", "Under Export Clearance"),
                    ("Departed", "Departed"),
                    ("In Transit", "In Transit"),
                    ("Arrived", "Arrived"),
                    ("Under Import Clearance", "Under Import Clearance"),
                    ("Do Collected", "Do Collected"),
                    ("Gate Pass Issued", "Gate Pass Issued"),
                    ("Under Delivery", "Under Delivery"),
                    ("In Warehouse Storage", "In Warehouse Storage"),
                    ("Delivered", "Delivered"),
                    ("Invoiced", "Invoiced"),
                    ("Finished", "Finished"),
                    ("Cancelled", "Cancelled"),
                    ("Air Freigt", "Air Freigt"),
                    ("Sea Freight", "Sea Freight"),
                    ("Land Freight", "Land Freight"),
                    ("Transportation", "Transportation"),
                    ("Warehousing", "Warehousing"),
                ],
                max_length=255,
                verbose_name="Job Status",
            ),
        ),
    ]
