# Generated by Django 4.2.3 on 2023-07-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0006_alter_job_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="container_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("20DC", "20’DC"),
                    ("20RF", "20’RF"),
                    ("20ST", "20’ST"),
                    ("20OT", "20’OT"),
                    ("20HC", "20’HC"),
                    ("40DC", "40’DC"),
                    ("40RF", "40’RF"),
                    ("40ST", "40’ST"),
                    ("40OT", "40’OT"),
                    ("40HC", "40’HC"),
                    ("FLAT_RACK", "FLAT RACK"),
                    ("FTL", "FTL"),
                    ("LTL", "LTL"),
                ],
                max_length=10,
                null=True,
                verbose_name="Container Type",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="scope_of_work",
            field=models.CharField(
                blank=True,
                choices=[
                    ("D2D", "D2D"),
                    ("EXW", "EXW"),
                    ("FOB", "FOB"),
                    ("CIF", "CIF"),
                    ("CNF", "CNF"),
                    ("C&F", "C&F"),
                    ("DDP", "DDP"),
                    ("DAP", "DAP"),
                    ("CPT", "CPT"),
                    ("TRANS", "TRANS"),
                    ("D-TRANS", "D-TRANS"),
                    ("OTHERS", "OTHERS"),
                ],
                max_length=255,
                null=True,
                verbose_name="Scope of Work ",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Air_Freight", "Air Freight"),
                    ("Sea_Freight", "Sea Freight"),
                    ("Land_Freight", "Land Freight"),
                    ("Transportation", "Transportation"),
                    ("Warehousing", "Warehousing"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
