# Generated by Django 4.2.3 on 2023-07-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0007_job_container_type_job_scope_of_work_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="por",
            field=models.TextField(blank=True, null=True),
        ),
    ]
