# Generated by Django 4.2.3 on 2023-07-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0007_job_container_type_job_scope_of_work_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Air_Freight", "Air Freight"),
                    ("Sea_Freight", "Sea Freight"),
                    ("Land_Freight", "Land Freight"),
                    ("Transportation", "Transportation"),
                    ("Warehousing", "Warehousing"),
                ],
                max_length=20,
                null=True,
                verbose_name="Freight Choice",
            ),
        ),
    ]
