# Generated by Django 4.2.3 on 2023-07-25 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0008_alter_job_type"),
        ("organization", "0008_job_por"),
    ]

    operations = []
