# Generated by Django 4.2.3 on 2023-07-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0009_merge_0008_alter_job_type_0008_job_por"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(blank=True, max_length=200, null=True)),
                ("Name", models.CharField(blank=True, max_length=200, null=True)),
                ("Status", models.BooleanField(blank=True, max_length=200, null=True)),
                ("Subledger_Requried", models.BooleanField(blank=True, max_length=200, null=True)),
                ("Charage_Required", models.BooleanField(blank=True, max_length=200, null=True)),
                ("Job_Required", models.BooleanField(blank=True, max_length=200, null=True)),
                ("Asset_Required", models.BooleanField(blank=True, max_length=200, null=True)),
                (
                    "coa_type",
                    models.CharField(choices=[("BS", "Balance Sheet"), ("PL", "Profit and Loss")], max_length=200),
                ),
                (
                    "Is_Direct_Indirect",
                    models.CharField(choices=[("Direct", "Direct"), ("Indirect", "Indirect")], max_length=200),
                ),
                ("DR_Cr", models.CharField(choices=[("Dr", "Dr"), ("Cr", "Cr")], max_length=200)),
                ("Category", models.CharField(blank=True, max_length=200, null=True)),
                ("Group", models.CharField(blank=True, max_length=200, null=True)),
                ("Subgroup", models.CharField(blank=True, max_length=200, null=True)),
                ("Type", models.CharField(blank=True, max_length=200, null=True)),
                ("Short_Name", models.CharField(blank=True, max_length=200, null=True)),
                ("Long_Name", models.CharField(blank=True, max_length=200, null=True)),
                ("Language_Name", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Air Freight", "Air Freight"),
                    ("Sea Freight", "Sea Freight"),
                    ("Land Freight", "Land Freight"),
                    ("Transportation", "Transportation"),
                    ("Warehousing", "Warehousing"),
                ],
                max_length=20,
                null=True,
                verbose_name="Freight Choice",
            ),
        ),
    ]
