# Generated by Django 4.2.3 on 2023-07-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0010_coa_alter_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="eta",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="etd",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coa",
            name="Asset_Required",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coa",
            name="Charage_Required",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coa",
            name="Job_Required",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coa",
            name="Status",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coa",
            name="Subledger_Requried",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
