# Generated by Django 4.2.3 on 2023-07-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0011_job_eta_job_etd_alter_coa_asset_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vouchers",
            name="voucher_type",
            field=models.CharField(
                choices=[
                    ("Journal", "Journal"),
                    ("Payment", "Payment"),
                    ("Receipt", "Receipt"),
                    ("CREDIT NOTE", "CREDIT NOTE"),
                    ("DEBIT NOTE", "Debit"),
                ],
                max_length=255,
                verbose_name="Voucher Type",
            ),
        ),
    ]
