# Generated by Django 4.2.3 on 2023-07-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0012_alter_vouchers_voucher_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Consignee", "Consignee"),
                    ("Client", "Client"),
                    ("Notify", "Notify"),
                    ("Shipper", "Shipper"),
                    ("Broker", "Broker"),
                    ("Transporter", "Transporter"),
                    ("Counterpart", "Counterpart"),
                    ("Coloader", "Coloader"),
                    ("Supplier", "Supplier"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
                verbose_name="Organization Type",
            ),
        ),
    ]
