# Generated by Django 4.2.3 on 2023-07-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0013_job_organization_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoaCategorymodel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("status", models.BooleanField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "dr_cr",
                    models.CharField(blank=True, choices=[("Dr", "Dr"), ("Cr", "Cr")], max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoaGroupmodels",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("type", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "dr_cr",
                    models.CharField(blank=True, choices=[("Dr", "Dr"), ("Cr", "Cr")], max_length=200, null=True),
                ),
                ("status", models.BooleanField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
