# Generated by Django 4.2.3 on 2023-07-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0014_coacategorymodel_coagroupmodels"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CoaCategorymodel",
            new_name="CoaCategory",
        ),
        migrations.RenameModel(
            old_name="CoaGroupmodels",
            new_name="CoaGroup",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="Category",
            new_name="additional_reference_code",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="Asset_Required",
            new_name="asset_required",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="Group",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="Charage_Required",
            new_name="charage_required",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="DR_Cr",
            new_name="dr_cr",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="Language_Name",
            new_name="group",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="Is_Direct_Indirect",
            new_name="is_direct_indirect",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="Job_Required",
            new_name="job_required",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="Long_Name",
            new_name="language_name",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="Name",
            new_name="long_name",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="Short_Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="Subgroup",
            new_name="short_name",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="Status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="Type",
            new_name="subgroup",
        ),
        migrations.RenameField(
            model_name="coa",
            old_name="Subledger_Requried",
            new_name="subledger_requried",
        ),
        migrations.AddField(
            model_name="coa",
            name="currency",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="coa",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coa",
            name="type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="coa",
            name="coa_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
