# Generated by Django 4.2.3 on 2023-07-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0015_rename_coacategorymodel_coacategory_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coa",
            old_name="charage_required",
            new_name="charge_required",
        ),
        migrations.AlterField(
            model_name="coa",
            name="is_direct_indirect",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
