# Generated by Django 4.2.3 on 2023-07-25 12:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0016_rename_charage_required_coa_charge_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="organization_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None
            ),
        ),
    ]
