# Generated by Django 4.2.3 on 2023-07-26 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0018_poa_pod_alter_job_organization_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("type", models.CharField(choices=[("Consignee", "Consignee"), ("Client", "Client")], max_length=200)),
                ("language_name", models.CharField(blank=True, max_length=200, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("vat_trn_number", models.CharField(blank=True, max_length=200, null=True)),
                ("website", models.CharField(blank=True, max_length=200, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("coa", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organization.coa")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organization.company")),
            ],
        ),
    ]
