# Generated by Django 4.2.3 on 2023-07-26 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_charge_alter_job_organization_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_cost', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('ex_rate', models.CharField(blank=True, max_length=200, null=True)),
                ('dr_cr', models.CharField(blank=True, max_length=200, null=True)),
                ('job_no', models.CharField(blank=True, max_length=200, null=True)),
                ('fcy_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('prorate_method', models.CharField(blank=True, max_length=200, null=True)),
                ('shipment_no', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('tax_group_code', models.CharField(blank=True, max_length=200, null=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.charge')),
            ],
        ),
    ]
