# Generated by Django 4.2.3 on 2023-07-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_costentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costentry',
            name='dr_cr',
            field=models.CharField(blank=True, choices=[('Dr', 'Dr'), ('Cr', 'Cr')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='costentry',
            name='job_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.job'),
        ),
    ]
