# Generated by Django 4.2.3 on 2023-07-26 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_alter_costentry_dr_cr_alter_costentry_job_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costentry',
            name='job_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.job'),
        ),
    ]
