# Generated by Django 4.2.3 on 2023-07-26 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0018_poa_pod_alter_job_organization_type"),
        ("organization", "0021_alter_costentry_job_no"),
    ]

    operations = []
