# Generated by Django 4.2.3 on 2023-07-26 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0019_organization"),
        ("organization", "0022_merge_20230726_0902"),
    ]

    operations = []
