# Generated by Django 4.2.3 on 2023-07-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0023_merge_0019_organization_0022_merge_20230726_0902"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
