# Generated by Django 4.2.3 on 2023-07-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0024_alter_charge_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
