# Generated by Django 4.2.3 on 2023-07-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0025_alter_charge_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="coa",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.coa"),
        ),
    ]
