# Generated by Django 4.2.3 on 2023-07-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0026_charge_coa"),
    ]

    operations = [
        migrations.AddField(
            model_name="charge",
            name="tax",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
