# Generated by Django 4.2.3 on 2023-07-28 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0027_charge_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="coagroup",
            name="voucher",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.vouchers"
            ),
        ),
    ]
