# Generated by Django 4.2.3 on 2023-07-28 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0028_coagroup_voucher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coagroup",
            name="voucher",
        ),
        migrations.AddField(
            model_name="coa",
            name="voucher",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.vouchers"
            ),
        ),
        migrations.AddField(
            model_name="vouchers",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vouchers",
            name="book",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vouchers",
            name="category",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="vouchers",
            name="currency",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="vouchers",
            name="ex_rate",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="vouchers",
            name="instrument_type",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="vouchers",
            name="party_state_code",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="vouchers",
            name="pay_to",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="vouchers",
            name="period",
            field=models.TextField(blank=True, null=True),
        ),
    ]
