# Generated by Django 4.2.3 on 2023-07-28 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0030_organization_branch_organization_building_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coa",
            name="voucher",
        ),
        migrations.AddField(
            model_name="coa",
            name="company",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.company"),
        ),
    ]
