# Generated by Django 4.2.3 on 2023-07-28 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0031_remove_coa_voucher_coa_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="costentry",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="costentry",
            name="invoice",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="organization.invoices"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoices",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="vouchers",
            name="party_account",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.coa"
            ),
        ),
    ]
