# Generated by Django 4.2.3 on 2023-07-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0032_costentry_created_at_costentry_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costentry",
            name="invoice",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.invoices"
            ),
        ),
    ]
