# Generated by Django 4.2.3 on 2023-07-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0033_alter_costentry_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costentry",
            name="invoice",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.invoices"
            ),
        ),
    ]
