# Generated by Django 4.2.3 on 2023-07-28 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0034_alter_costentry_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoices",
            name="last_time_generated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
