# Generated by Django 4.2.3 on 2023-07-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0036_vouchers_ref_date_vouchers_ref_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="costentry",
            name="is_included",
            field=models.BooleanField(default=False),
        ),
    ]
