# Generated by Django 4.2.3 on 2023-08-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0037_costentry_is_included"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="pol",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
