# Generated by Django 4.2.3 on 2023-08-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0038_job_pol"),
    ]

    operations = [
        migrations.AddField(
            model_name="costentry",
            name="voucher",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.vouchers"
            ),
        ),
    ]
