# Generated by Django 4.2.3 on 2023-08-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0039_costentry_voucher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costentry",
            name="voucher",
        ),
        migrations.AddField(
            model_name="costentry",
            name="voucher_type",
            field=models.CharField(
                choices=[
                    ("Journal", "Journal"),
                    ("Payment", "Payment"),
                    ("Receipt", "Receipt"),
                    ("CREDIT NOTE", "CREDIT NOTE"),
                    ("DEBIT NOTE", "DEBIT NOTE"),
                ],
                default=None,
                max_length=255,
                verbose_name="Voucher Type",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vouchers",
            name="voucher_type",
            field=models.CharField(
                choices=[
                    ("Journal", "Journal"),
                    ("Payment", "Payment"),
                    ("Receipt", "Receipt"),
                    ("CREDIT NOTE", "CREDIT NOTE"),
                    ("DEBIT NOTE", "DEBIT NOTE"),
                ],
                max_length=255,
                verbose_name="Voucher Type",
            ),
        ),
    ]
