# Generated by Django 4.2.3 on 2023-08-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0040_remove_costentry_voucher_costentry_voucher_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costentry",
            name="voucher_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Journal", "Journal"),
                    ("Payment", "Payment"),
                    ("Receipt", "Receipt"),
                    ("CREDIT NOTE", "CREDIT NOTE"),
                    ("DEBIT NOTE", "DEBIT NOTE"),
                ],
                max_length=255,
                null=True,
                verbose_name="Voucher Type",
            ),
        ),
    ]
