# Generated by Django 4.2.3 on 2023-08-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0041_alter_costentry_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poa',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='poa',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pod',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pod',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
