# Generated by Django 4.2.3 on 2023-08-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0042_poa_code_poa_country_pod_code_pod_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poa',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='poa',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pod',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pod',
            name='country',
            field=models.CharField(max_length=255),
        ),
    ]
