# Generated by Django 4.2.3 on 2023-08-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0044_company_account_name_company_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="vat",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="invoices",
            name="consignee_name",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="organization.organization"
            ),
            preserve_default=False,
        ),
    ]
