# Generated by Django 4.2.3 on 2023-08-04 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0045_company_vat_alter_invoices_consignee_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoices",
            old_name="consignee_name",
            new_name="consignee",
        ),
    ]
