# Generated by Django 4.2.3 on 2023-08-04 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0046_rename_consignee_name_invoices_consignee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoices",
            name="consignee",
        ),
        migrations.AddField(
            model_name="invoices",
            name="client_name",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientinvoice",
                to="organization.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoices",
            name="consignee_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consigneename_Invoice",
                to="organization.organization",
            ),
            preserve_default=False,
        ),
    ]
