# Generated by Django 4.2.3 on 2023-08-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0047_remove_invoices_consignee_invoices_client_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="gstin_registered",
            field=models.BooleanField(default=False),
        ),
    ]
