# Generated by Django 4.2.3 on 2023-08-18 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0048_alter_organization_gstin_registered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coa",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="organization.coagroup",
            ),
        ),
        migrations.AlterField(
            model_name="coa",
            name="subgroup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_groups",
                to="organization.coagroup",
            ),
        ),
        migrations.AlterField(
            model_name="coagroup",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EQUITY", "EQUITY"),
                    ("ASSET", "ASSET"),
                    ("EXPENSE", "EXPENSE"),
                    ("INCOME", "INCOME"),
                    ("LIABILITY", "LIABILITY"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Air Freight", "Air Freight"),
                    ("Sea Freight", "Sea Freight"),
                    ("Land Freight", "Land Freight"),
                    ("Transportation", "Transportation"),
                    ("Warehousing", "Warehousing"),
                    ("Customs Clearance", "Customs Clearance"),
                    (" Other", " Other"),
                ],
                max_length=20,
                null=True,
                verbose_name="Freight Choice",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=models.CharField(
                choices=[
                    ("Consignee", "Consignee"),
                    ("Client", "Client"),
                    ("Supplier", "Supplier"),
                    ("Shipper", "Shipper"),
                    ("Notify", "Notify"),
                    ("Counterpart", "Counterpart"),
                    ("Broker", "Broker"),
                    ("Agents", "Agents"),
                    ("Others", "Others"),
                ],
                max_length=200,
            ),
        ),
    ]
