# Generated by Django 4.2.3 on 2023-08-18 06:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0049_alter_coa_group_alter_coa_subgroup_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None
            ),
        ),
    ]
