# Generated by Django 4.2.3 on 2023-08-18 06:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0050_alter_organization_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, null=True, size=None
            ),
        ),
    ]
