# Generated by Django 4.2.3 on 2023-08-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0051_alter_organization_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="coagroup",
            name="language_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
