# Generated by Django 4.2.3 on 2023-08-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0052_coagroup_language_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="client_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_name_jobs",
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="consignee_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consignee_name_jobs",
                to="organization.organization",
            ),
        ),
    ]
