# Generated by Django 4.2.3 on 2023-08-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0053_alter_job_client_name_alter_job_consignee_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoices",
            name="client_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientinvoice",
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="invoices",
            name="consignee_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consigneename_Invoice",
                to="organization.organization",
            ),
        ),
    ]
