# Generated by Django 4.2.3 on 2023-08-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0054_alter_invoices_client_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoices",
            name="language_address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
