# Generated by Django 4.2.3 on 2023-08-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0055_invoices_language_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="parties",
            field=models.ManyToManyField(blank=True, null=True, to="organization.organization"),
        ),
    ]
