# Generated by Django 4.2.3 on 2023-08-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0056_job_parties"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="language_address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="language_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="language_address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
