# Generated by Django 4.2.3 on 2023-08-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0057_company_language_address_company_language_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="wat_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
