# Generated by Django 4.2.3 on 2023-08-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0058_company_wat_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="wat_number",
            new_name="company_name_lang",
        ),
        migrations.AddField(
            model_name="company",
            name="vat_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
