# Generated by Django 4.2.3 on 2023-08-25 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0059_rename_wat_number_company_company_name_lang_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoices",
            name="party_account",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.organization"
            ),
        ),
    ]
