# Generated by Django 4.2.3 on 2023-08-29 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0060_invoices_party_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="broker_jobs",
                to="organization.organization",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="client_ref",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="commodity",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="notify",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notify_jobs",
                to="organization.organization",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="quantity_text",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="transporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transporter_jobs",
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="container_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("20DC", "20’DC"),
                    ("20RF", "20’RF"),
                    ("20ST", "20’ST"),
                    ("20OT", "20’OT"),
                    ("20HC", "20’HC"),
                    ("40DC", "40’DC"),
                    ("40RF", "40’RF"),
                    ("40ST", "40’ST"),
                    ("40OT", "40’OT"),
                    ("40HC", "40’HC"),
                    ("FLAT_RACK", "FLAT RACK"),
                    ("FTL", "FTL"),
                    ("LTL", "LTL"),
                    ("Pallets", "Pallets"),
                    ("Boxes", "Boxes"),
                    ("Cartons", "Cartons"),
                ],
                max_length=10,
                null=True,
                verbose_name="Container Type",
            ),
        ),
    ]
