# Generated by Django 4.2.3 on 2023-09-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0061_job_broker_job_client_ref_job_commodity_job_notify_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vouchers",
            name="voucher_from",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vouchers",
            name="voucher_from_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vouchers",
            name="voucher_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vouchers",
            name="voucher_to_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
