# Generated by Django 4.2.3 on 2023-09-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0062_vouchers_voucher_from_vouchers_voucher_from_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="pinv_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="sinv_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="invoices",
            name="invoice_number",
            field=models.CharField(default="NA", max_length=255),
        ),
    ]
