# Generated by Django 4.2.3 on 2023-09-08 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0063_company_pinv_count_company_sinv_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costentry",
            name="invoice",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="organization.invoices"
            ),
        ),
    ]
