# Generated by Django 4.2.3 on 2023-09-08 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0064_alter_costentry_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vouchers",
            name="job",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.job"
            ),
        ),
        migrations.AlterField(
            model_name="vouchers",
            name="voucher_type",
            field=models.CharField(
                choices=[
                    ("Journal", "Journal"),
                    ("Payment", "Payment"),
                    ("Receipt", "Receipt"),
                    ("Credit Note", "Credit Note"),
                    ("Debit Note", "Debit Note"),
                ],
                max_length=255,
                verbose_name="Voucher Type",
            ),
        ),
    ]
