# Generated by Django 4.2.3 on 2023-09-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0065_alter_vouchers_job_alter_vouchers_voucher_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vouchers",
            name="voucher_type",
            field=models.CharField(
                choices=[
                    ("Journal", "Journal"),
                    ("Payment", "Payment"),
                    ("Receipt", "Receipt"),
                    ("CreditNote", "CreditNote"),
                    ("DebitNote", "DebitNote"),
                ],
                max_length=255,
                verbose_name="Voucher Type",
            ),
        ),
    ]
