# Generated by Django 4.2.3 on 2023-09-08 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0066_alter_vouchers_voucher_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.company"),
        ),
    ]
