# Generated by Django 4.2.3 on 2023-09-08 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0067_alter_job_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="vouchers",
            name="company",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.company"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to="organization.company"
            ),
            preserve_default=False,
        ),
    ]
