# Generated by Django 4.2.3 on 2023-09-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0068_vouchers_company_alter_job_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDetails",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("line_no", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "dr_cr",
                    models.CharField(blank=True, choices=[("Dr", "Dr"), ("Cr", "Cr")], max_length=200, null=True),
                ),
                ("narration", models.CharField(blank=True, max_length=200, null=True)),
                ("qty", models.CharField(blank=True, max_length=200, null=True)),
                ("currency", models.CharField(blank=True, max_length=200, null=True)),
                ("ex_rate", models.CharField(blank=True, max_length=200, null=True)),
                ("amount_qty", models.CharField(blank=True, max_length=200, null=True)),
                ("fcy_amount", models.CharField(blank=True, max_length=200, null=True)),
                ("amount_sar", models.CharField(blank=True, max_length=200, null=True)),
                ("tax_group_code", models.CharField(blank=True, max_length=200, null=True)),
                ("taxable_amount", models.CharField(blank=True, max_length=200, null=True)),
                ("tax_amount", models.CharField(blank=True, max_length=200, null=True)),
                ("division", models.CharField(blank=True, max_length=200, null=True)),
                ("asset", models.CharField(blank=True, max_length=200, null=True)),
                ("inter_branch", models.CharField(blank=True, max_length=200, null=True)),
                ("sac_code", models.CharField(blank=True, max_length=200, null=True)),
                ("remarks", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "ac_name",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.coa"),
                ),
                (
                    "vouchers",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.vouchers"
                    ),
                ),
            ],
        ),
    ]
