# Generated by Django 4.2.3 on 2023-09-11 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0069_accountdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountdetails",
            name="department",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="accountdetails",
            name="job_no",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.job"
            ),
        ),
        migrations.AddField(
            model_name="accountdetails",
            name="shipment_no",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
