# Generated by Django 4.2.3 on 2023-09-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0070_accountdetails_department_accountdetails_job_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vouchers",
            name="invoice",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.invoices"
            ),
        ),
    ]
