# Generated by Django 4.2.3 on 2023-09-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0071_vouchers_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_status",
            field=models.CharField(
                choices=[
                    ("Cargo Collected", "Cargo Collected"),
                    ("Under Export Clearance", "Under Export Clearance"),
                    ("Departed", "Departed"),
                    ("In Transit", "In Transit"),
                    ("Arrived", "Arrived"),
                    ("Under Import Clearance", "Under Import Clearance"),
                    ("Do Collected", "Do Collected"),
                    ("Gate Pass Issued", "Gate Pass Issued"),
                    ("Under Delivery", "Under Delivery"),
                    ("In Warehouse Storage", "In Warehouse Storage"),
                    ("Delivered", "Delivered"),
                    ("Invoiced", "Invoiced"),
                    ("Finished", "Finished"),
                    ("Cancelled", "Cancelled"),
                    ("RFQ", "RFQ"),
                ],
                max_length=255,
                verbose_name="Job Status",
            ),
        ),
    ]
