# Generated by Django 4.2.3 on 2023-09-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0072_alter_job_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vouchers",
            name="party_account_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vouchers",
            name="party_account",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
