# Generated by Django 4.2.3 on 2023-09-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0073_vouchers_party_account_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoices",
            name="branch",
            field=models.CharField(blank=True, default="JEDDAH", max_length=255, null=True),
        ),
    ]
