# Generated by Django 4.2.3 on 2023-09-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0074_invoices_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoices",
            name="supplier_inv_number",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
