# Generated by Django 4.2.3 on 2023-09-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0075_invoices_supplier_inv_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountdetails",
            name="ac_name_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="accountdetails",
            name="ac_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
