# Generated by Django 4.2.3 on 2023-09-25 05:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0076_accountdetails_ac_name_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoices",
            name="paid_amount",
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoices",
            name="paid_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="invoices",
            name="payment_status",
            field=models.CharField(blank=True, default="Unpaid", max_length=255, null=True),
        ),
    ]
