# Generated by Django 4.2.3 on 2023-09-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0077_invoices_paid_amount_invoices_paid_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoices",
            name="coa",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="organization.coa"
            ),
        ),
    ]
