# Generated by Django 4.2.3 on 2023-10-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0079_alter_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Air Freight", "Air Freight"),
                    ("Sea Freight", "Sea Freight"),
                    ("Land Freight", "Land Freight"),
                    ("Transportation", "Transportation"),
                    ("Warehousing", "Warehousing"),
                    ("Customs Clearance", "Customs Clearance"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
                verbose_name="Freight Choice",
            ),
        ),
    ]
