# Generated by Django 3.2.21 on 2023-10-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0080_alter_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enquiry_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='job_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
