# Generated by Django 4.2.3 on 2023-11-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0081_auto_20231031_1349"),
    ]

    operations = [
        migrations.AddField(
            model_name="vouchers",
            name="voucher_for",
            field=models.CharField(
                blank=True,
                choices=[("Customer", "Customer"), ("Vendor", "Vendor")],
                max_length=255,
                null=True,
                verbose_name="Voucher For",
            ),
        ),
    ]
