# Generated by Django 4.2.3 on 2023-11-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0082_vouchers_voucher_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="costentry",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="job",
            name="container_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("20DC", "20’DC"),
                    ("20RF", "20’RF"),
                    ("20ST", "20’ST"),
                    ("20OT", "20’OT"),
                    ("20HC", "20’HC"),
                    ("40DC", "40’DC"),
                    ("40RF", "40’RF"),
                    ("40ST", "40’ST"),
                    ("40OT", "40’OT"),
                    ("40HC", "40’HC"),
                    ("40HQ", "40’HC"),
                    ("FLAT_RACK", "FLAT RACK"),
                    ("FTL", "FTL"),
                    ("LTL", "LTL"),
                    ("Pallets", "Pallets"),
                    ("Boxes", "Boxes"),
                    ("Cartons", "Cartons"),
                ],
                max_length=10,
                null=True,
                verbose_name="Container Type",
            ),
        ),
    ]
