# Generated by Django 4.2.3 on 2023-11-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0083_costentry_quantity_alter_job_container_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="job",
            name="isdeleted",
            field=models.BooleanField(default=False),
        ),
    ]
