# Generated by Django 4.2.3 on 2023-11-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0084_remove_job_is_deleted_job_isdeleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costentry",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
