# Generated by Django 4.2.3 on 2023-12-13 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0085_alter_costentry_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountdetails",
            name="charge",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="organization.charge"
            ),
        ),
    ]
