# Generated by Django 4.2.3 on 2024-01-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0086_accountdetails_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="creditnote_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="debitnote_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="journal_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="payment_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="receipt_count",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vouchers",
            name="voucher_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
