# Generated by Django 4.2.3 on 2024-03-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0087_company_creditnote_count_company_debitnote_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
