# Generated by Django 4.2.3 on 2024-03-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0088_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="invoice_template",
            field=models.CharField(default="INV1"),
        ),
    ]
