# Generated by Django 4.2.3 on 2026-01-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0089_company_invoice_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="invoice_template",
            field=models.CharField(default="INV1", max_length=50),
        ),
    ]
