# Generated by Django 4.2.3 on 2023-07-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Fname of User"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Lname of User"),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Mobile of User"),
        ),
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name="user otp"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=255, verbose_name="Email of User"),
        ),
    ]
